#include "wsl_resources.h"

#include "../plugins/wsl_tools/wsl_common.h"
#include "mcp_resource.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace mcp_ext {

namespace {

bool is_safe_scan_id(const std::string& scan_id) {
    return !scan_id.empty() && std::all_of(scan_id.begin(), scan_id.end(), [](unsigned char c) {
        return std::isalnum(c) || c == '_' || c == '-';
    });
}

std::string read_file(const std::filesystem::path& path) {
    std::ifstream in(path);
    if (!in.is_open()) {
        throw mcp::mcp_exception(
            mcp::error_code::invalid_params,
            "WSL resource not found: " + path.string());
    }

    std::stringstream buffer;
    buffer << in.rdbuf();
    return buffer.str();
}

mcp::json read_report_resource(
    const std::string& uri,
    const std::string& scan_id,
    const std::string& suffix,
    const std::string& name) {

    if (!is_safe_scan_id(scan_id)) {
        throw mcp::mcp_exception(mcp::error_code::invalid_params, "Invalid scan_id");
    }

    std::filesystem::path path = mcp_ext::wsl::reports_directory() /
        (scan_id + suffix);

    mcp::text_resource resource(uri, name, "application/json");
    resource.set_text(read_file(path));
    return resource.read();
}

} // namespace

void register_wsl_resources(mcp::server& server) {
    server.register_resource_template(
        "wsl://scan/{scan_id}/report",
        "WSL scan report",
        "application/json",
        "JSON report generated by wsl_scan_files.",
        [](const std::string& uri,
           const std::map<std::string, std::string>& uri_params,
           const std::string& /* session_id */) -> mcp::json {
            return read_report_resource(
                uri,
                uri_params.at("scan_id"),
                "_report.json",
                "WSL scan report");
        });

    server.register_resource_template(
        "wsl://scan/{scan_id}/recommendations",
        "WSL cleanup recommendations",
        "application/json",
        "JSON cleanup recommendations generated by wsl_recommend_cleanup.",
        [](const std::string& uri,
           const std::map<std::string, std::string>& uri_params,
           const std::string& /* session_id */) -> mcp::json {
            return read_report_resource(
                uri,
                uri_params.at("scan_id"),
                "_recommendations.json",
                "WSL cleanup recommendations");
        });
}

} // namespace mcp_ext
